# Project information
site_name: MySQL
site_description: MySQL学習のメモ書き
site_author: Shuji Narumi
# site_url: 


# Copyright
copyright: Copyright (c) 2021 bonji@mikuro.net

# Documentation and theme
docs_dir: docs
theme:
  name: material
  logo: images/logo_w.svg
  favicon : images/logo_w.svg
  features:
    - navigation.instant
  language: ja

markdown_extensions:
  - admonition # 注意書きやノート:  !!! note ""
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      toc_depth: 2
      permalink: true



# 
nav:
    - データベースの基礎力:
        - MySQLへの接続: database_basics/mysql_for_the_first_time.md
        - データベースとSQLの概要: database_basics/database_and_sql_overview.md
        - データベースの追加: database_basics/add_database.md
        - データの追加と更新: database_basics/add_and_update_data.md
    #     - SQLコーディングノウハウ: database_basics/sql_coding_know-how.md
        - テーブル作成の応用設定: database_basics/advanced_settings_for_table_creation.md
        - データベース構築演習: database_basics/database_construction_exercise.md
    - SQLデータ解析ノウハウ:
        - データベースの復元: SQL_data_analysis_know-how/database_restore.md
        - データ抽出のノウハウ: SQL_data_analysis_know-how/data_extraction_know-how.md
        - 論理演算子を利用した条件文: SQL_data_analysis_know-how/conditional_statement_using_logical_operators.md
        - SQLで利用できる関数: SQL_data_analysis_know-how/functions_available_in_sql.md
        - テーブル結合: SQL_data_analysis_know-how/table_join.md
        - VIEWの活用: SQL_data_analysis_know-how/utilization_of_view.md
        - サブクエリの活用: SQL_data_analysis_know-how/utilization_of_subqueries.md
        # - ストアドプロシージャの活用: SQL_data_analysis_know-how/utilization_of_stored_procedures.md
    - SQLの復習（勘所）:
        - データの参照: memo/data_reference.md
        - レコードの更新: memo/record_update.md
        - テーブルの操作: memo/table_operation.md
        - その他: memo/others.md
    - etc:
        - INDEX: etc/about_index.md
        - 文字コードについて: etc/char.md
        - 環境変更: etc/environmental_setting.md
        - 課題: etc/practice.md
